### ISSUE TITLE
Incompatible with latest vesion of QGIS

### ISSUE THREAD

**Issue by Rigonz** [ksolsrl/QgisIso4app#1]
Message from 3.0.1-Girona
"
This plugin is incompatible with this version of QGIS
Plugin designed for QGIS 2.18.16 - 2.99
"

**Comment by ksolsrl** [comment]
As soon as possible a version compatible with 3.x version will be released!

**Comment by ksolsrl** [comment]
The latest iso4app plugin is compatible with QGIS 3.X
